name: Test Actions

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: read

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

     

    - name: install dependencies  
      run: yarn

    - name: Danger js check  
      run: yarn danger ci  
      env:
        GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }} 

    - name: Test
      run: yarn test --coverage

    - name: Check linting
      run: yarn lint  

    - name: Check commit message
      uses: wagoid/commitlint-github-action@v5 

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      
      env:
        CI: true