name: Test Actions

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: read

jobs: 
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: install dependencies  
      run: yarn

    - name: Test
      run: yarn test --coverage

    - name: Check linting
      run: yarn lint  

    - name: Check commit message
      uses: wagoid/commitlint-github-action@v5   

      env:
        CI: true